<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net48</TargetFramework>
    <AllowUnsafeBlocks>true</AllowUnsafeBlocks>
    <LangVersion>latest</LangVersion>
    <Nullable>disable</Nullable>
    <RootNamespace>AzuCraftyBoxes</RootNamespace>
    <AssemblyName>AzuCraftyBoxes</AssemblyName>
    <GenerateAssemblyInfo>false</GenerateAssemblyInfo>
    <Deterministic>true</Deterministic>
  </PropertyGroup>
  <ItemGroup>
    <Reference Include="BepInEx">
      <HintPath>GameLibs/BepInEx.dll</HintPath>
    </Reference>
    <Reference Include="0Harmony">
      <HintPath>GameLibs/0Harmony.dll</HintPath>
    </Reference>
    <Reference Include="assembly_valheim">
      <HintPath>GameLibs/assembly_valheim.dll</HintPath>
    </Reference>
    <Reference Include="assembly_utils">
      <HintPath>GameLibs/assembly_utils.dll</HintPath>
    </Reference>
    <Reference Include="assembly_guiutils">
      <HintPath>GameLibs/assembly_guiutils.dll</HintPath>
    </Reference>
    <Reference Include="Backpacks">
      <HintPath>Libs/BackpacksAPI.dll</HintPath>
    </Reference>
    <Reference Include="EpicLootAPI">
      <HintPath>Libs/EpicLootAPI.dll</HintPath>
    </Reference>
    <Reference Include="ItemDataManager">
      <HintPath>Libs/ItemDataManager.dll</HintPath>
    </Reference>
    <Reference Include="Jewelcrafting">
      <HintPath>Libs/JewelcraftingAPI.dll</HintPath>
    </Reference>
    <Reference Include="ServerSync">
      <HintPath>Libs/ServerSync.dll</HintPath>
    </Reference>
    <Reference Include="UnityEngine">
      <HintPath>GameLibs/UnityEngine.dll</HintPath>
    </Reference>
    <Reference Include="UnityEngine.CoreModule">
      <HintPath>GameLibs/UnityEngine.CoreModule.dll</HintPath>
    </Reference>
    <Reference Include="UnityEngine.AssetBundleModule">
      <HintPath>GameLibs/UnityEngine.AssetBundleModule.dll</HintPath>
    </Reference>
    <Reference Include="UnityEngine.IMGUIModule">
      <HintPath>GameLibs/UnityEngine.IMGUIModule.dll</HintPath>
    </Reference>
    <Reference Include="UnityEngine.InputLegacyModule">
      <HintPath>GameLibs/UnityEngine.InputLegacyModule.dll</HintPath>
    </Reference>
    <Reference Include="UnityEngine.UI">
      <HintPath>GameLibs/UnityEngine.UI.dll</HintPath>
    </Reference>
    <Reference Include="Unity.TextMeshPro">
      <HintPath>GameLibs/Unity.TextMeshPro.dll</HintPath>
    </Reference>
    <Reference Include="UnityEngine.PhysicsModule">
      <HintPath>GameLibs/UnityEngine.PhysicsModule.dll</HintPath>
    </Reference>
  </ItemGroup>
  <ItemGroup>
    <EmbeddedResource Include="Example.yml" />
    <EmbeddedResource Include="images\pullingicon.png" />
    <EmbeddedResource Include="translations\English.yml" />
  </ItemGroup>
  <ItemGroup>
    <PackageReference Include="Microsoft.NETFramework.ReferenceAssemblies.net48" Version="1.0.3">
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
      <PrivateAssets>all</PrivateAssets>
    </PackageReference>
    <PackageReference Include="YamlDotNet" Version="16.3.0" />
  </ItemGroup>
</Project>
